MarcusO17/CallADoctor-5001CEM

api/backendAPI.py, db/dbhelper.py
added new registration columns for db
=> Db refactor

src/DoctorRegister.py
Adding code to save the data of Doctor Register Page
=> DATA SAVER for Doc

src/ClinicRegister.py, src/DoctorRegister.py
Made necessary changes and wrote code for saving data of Clinic Registration
=> PR Fix clinic register

src/ClinicRegister.py, src/DoctorRegister.py, src/PatientRegister.py
Fixed all the necessary things in Patient Registration Page, and also wrote the code for saving patient data.
=> PR Fix patient register

src/ClinicRegister.py, src/DoctorHomePage.py, src/DoctorRegister.py, src/PatientRegister.py
I made the changes per the comments and resized the window per Kelvin's Patient Homepage.
=> Fix doctor home page

src/PatientClinicsNearbyWindow.py, src/PatientHomepage.py, src/model/Clinic.py, src/model/__init__.py
=> Feature patient clinicsnearby

src/ClinicHomepage.py, src/LoginWindow.py
Basic clinic homepage ready for merge
=> Feature clinic homepage

src/LoginWindow.py, src/PatientClinicDetailsWindow.py, src/PatientClinicsNearbyWindow.py, src/PatientHomepage.py, src/PatientSendRequest.py, src/model/Clinic.py
=> Feature patient send request

src/ClinicHomepage.py, src/DoctorScheduleWindow.py, src/LoginWindow.py, src/PatientHomepage.py, src/main.py, src/model/Clinic.py, src/model/Login.py, src/model/Patient.py
connected BE to Login and multiple role screens
=> Feature login wiring

src/PatientPrescription.py, src/PatientPrescriptionDetails.py, src/model/Prescription.py, src/model/__init__.py
For Patient View created Prescription Selection Page, and Prescription Details Page. Sending a Pull Request, because need to sync from main to get model of the Doctor, so I am going to create a new branch to link the doctor model to the page.
=> PR Feature patient prescription

api/backendAPI.py
=> fixed patient posting

src/AssignDoctorDialog.py, src/ClinicHomepage.py, src/ClinicRequestDetails.py, src/ClinicRequestReview.py
=> Feature clinic request review

api/backendAPI.py, src/model/Doctor.py, src/model/DoctorRepo.py
=> Feature doctor login

src/model/Prescription.py, src/model/PrescriptionDetails.py
=> added prescriptionDetails model

src/PatientPrescription.py, src/PatientPrescriptionDetails.py, src/model/PrescriptionDetails.py, src/model/PrescriptionRepo.py
Made necessary changes, hope the thing works now
=> PR Hotfix for PatientPrescription Page

src/AssignDoctorDialog.py, src/ClinicManageSchedule.py, src/model/Doctor.py
=> Fixed model

src/PatientAppointmentDetails.py, src/PatientHomepage.py, src/PatientMyAppointment.py, src/tempCodeRunnerFile.py
Patient My Appointment page and Patient Appointment Details Completed. 
Added Cancel Appointment Function.
=> PR Feature patient my appointment

src/ClinicAppointmentDetails.py, src/ClinicDetailedSchedule.py, src/DoctorHomepage.py, src/DoctorScheduleWindow.py
=> Feature schedule update

setup.py, src/ClinicAppointmentDetails.py, src/ClinicDetailedSchedule.py, src/ClinicManageSchedule.py, src/model/Appointment.py, src/model/AppointmentRepo.py, src/model/ClinicRepo.py, src/model/DoctorRepo.py
Integrate Appointment Schedule with DB via API
=> Integrate schedule appointment

src/ClinicRequestDetails.py, src/ClinicRequestReview.py
clinic request review, refreshed upon accepting or cancelling
=> Clinic Request Review Fixed

src/ClinicAddDoctor.py, src/ClinicDoctorList.py, src/ClinicManageSchedule.py, src/PatientClinicsNearbyWindow.py, src/model/PrescriptionRepo.py, src/model/__init__.py
=> Feature clinic add doctor search bar

api/backendAPI.py, api/tempCodeRunnerFile.py, src/model/AppointmentRepo.py, src/model/Prescription.py, src/model/PrescriptionRepo.py
small addition, remaking branch after this PR, delete after merge
=> added Posting prescriptions

api/backendAPI.py, run.py, src/ClinicAddDoctor.py, src/ClinicDoctorDetails.py, src/ClinicDoctorList.py, src/model/DoctorRepo.py
get Dctor List integrated with DB
=> Integrate doctor list

src/AdminHomePage.py
Created the Admin Home Page window, But need to change a few things when i add the next pages.
=> PR Feature admin home page

src/AdminViewClinicDetails.py
Made the code of Admin View Clinic Detials Page, could require some changes later.
Also, haven't linked the page to the previous one, waiting for PR approval
=> PR Feature admin view clinic details

src/AdminViewClinics.py
Created a page for Admin view - Viewing Clinic window. need to uncomment some things when the next pages are made.
=> Feature admin view clinics

src/model/Appointment.py, src/model/Clinic.py, src/model/Patient.py, tests/test_appointments.py, tests/test_clinic.py, tests/test_patient.py
=> Test models pr58

src/PatientAppointmentDetails.py, src/PatientHomepage.py, src/PatientMyAppointment.py, src/PatientPrescription.py, src/PatientPrescriptionDetails.py
=> Feature patient view prescription update

src/DoctorScheduleWindow.py
schedule appointment button works now
=> Connected Schedule to Appointment Details

src/ClinicRegister.py, src/DoctorRegister.py, src/LoginWindow.py, src/PatientRegister.py
This fix allows user to go to Registration page, not only that, but firsts asks the user which registration page he wants to go
=> PR Fix login to register

src/PatientRegister.py
The whole code looks edited, thats becuase Indentation was wrong, now its fixed, and lowercased the initial of variables too. Other than that, assigned "setPlaceHolderText" for line edits. and gave functions to both buttons
=> PR Fix patient register page

src/PatientRegister.py
Cleaned the StyleSheet of Patient Register page. Implemented functions to hide the passwords (normal and ReEnter), Added checkbox to show passwords. Validating the passwords to be same.
=> PR Fix patient register style sheet

src/ClinicRegister.py
Fixed Clinic Register Page - all variable initials made lowercase, Used setPlaceholdertext for all LineEdits, Added GoBackLogin Function, Added Register Button function (to save data and go to login window), Made the Style sheet code of the buttons way cleaner and simpler, Added function to hide Passwords (normal and ReEnter), Added function to Change color of ReEnter Field if password wrong or correct.
=> PR Fix clinic register page

src/DoctorRegister.py
I have fixed the doctor page for now - all variable initials made lowercase, Used setPlaceholdertext for all LineEdits, Added GoBackLogin Function, Added Register Button function (to save data and go to login window), Made the Style sheet code of the buttons way cleaner and simpler.
=> PR Fix doctor register page

src/ClinicRegister.py
Removed Clinic ID, Replaced some field in place of it, Adding function to store Documents. Added Function to remove document.
=> PR Fix clinic register columns

src/DoctorRegister.py
made necessary change - fixed stylesheet error, implemented hide  and show password functions, Implemented document upload function, implemented passwords validation, lowered the position of the Register and GobackLogin button.
=> PR Fix doctor register documents

src/PatientRegister.py
Added two new columns for Race and Blood Type, changed some old columns position to add in the new ones.
=> PR Fix patient register columns

src/LoginWindow.py
=> PR Fix login window message box

src/AdminClinicApproval.py, src/AdminHomePage.py, src/AdminViewApprovals.py, src/AdminViewClinicDetails.py, src/AdminViewClinics.py
Completed Admin Pages (Admin Homepage, Admin view Clinics -> Admin View Clinic Details, Admin view approvals -> Admin view Clinic Approval. 
Marcus needs to do backend.
=> PR Feature admin approval

api/backendAPI.py
=> requestsID Change

api/backendAPI.py, setup.py, src/ClinicRegister.py, src/DoctorRegister.py, src/model/Registration.py
added clinic registration + file upload
=> Feature login integrate

api/backendAPI.py, db/dbhelper.py, src/model/Request.py
=> Feature request upgrade

src/PatientSendRequest.py
=> Patient Send Request Fixed

api/backendAPI.py, src/AccountPage.py
=> added edit address

db/dbhelper.py, src/model/Request.py
=> db issues, fix requests

api/backendAPI.py
fixed requests showing more than needed
=> fixed request query
